#
# Executes commands at the start of an interactive session.
#
# Uses zgen: https://github.com/tarjoilija/zgen

# Source zgen
source "${ZGEN_DIR}/zgen.zsh"

# Only build zgen init if required
if ! zgen saved; then
  echo "Creating zgen save"

  # Specify Prezto & Plugins
  zgen prezto
  zgen prezto '*:*' color 'yes'
  zgen prezto prompt theme 'pure'  
  zgen prezto archive
  zgen prezto node
  zgen prezto command-not-found
  zgen prezto osx
  zgen prezto docker
  zgen prezto gpg
  #zgen prezto history
  zgen prezto homebrew
  zgen prezto utility

  zgen load ${DOTFILES_DIR}/shell/zsh

  zgen prezto git
  zgen prezto git status ignore submodules 'all'  

  zgen prezto ssh load identities 'id_rsa'

  zgen prezto syntax-highlighting
  zgen prezto syntax highlighting highlighters 'main' 'brackets' 'pattern'

  zgen prezto history-substring-search
  zgen prezto autosuggestions

  # Window title format
  zgen prezto terminal window-title format '%n@%m: %s'

  # Tab title format
  zgen prezto terminal tab-title format '%m: %s'

  # Auto start a session when Zsh is launched in a local terminal.
  zgen prezto tmux auto-start local 'yes'

  # Auto start a session when Zsh is launched in a SSH connection.
  zgen prezto tmux auto-start remote 'yes'

  # Integrate with iTerm2.
  zgen prezto tmux iterm integrate 'yes'

  # TODO: Move to script
  #test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

  zgen load supercrabtree/k
  zgen load marzocchi/zsh-notify
  zgen load djui/alias-tips

  # 
  # NVM
  #

  # Lazy load NVM
  export NVM_LAZY_LOAD=true

  #
  # Java
  #
  export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)";

  # ZSH NVM
  zgen load lukechilds/zsh-nvm

  #
  # ZGEN
  #

  # Autoupdate for zgen
  zgen load unixorn/autoupdate-zgen

  # 
  # Final Plugins
  # 
  zgen prezto completion

  # generate the init script from plugins above
  zgen save
fi



